version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/WhaleBot
permissions:
 - object: /home/ec2-user/WhaleBot
   pattern: "*"
   owner: ec2-user
   mode: 744
   type:
    - file
 - object: /home/ec2-user/WhaleBot
   pattern: "./"
   owner: ec2-user
   mode: 744
   type:
    - directory
 - object: /home/ec2-user/WhaleBot
   pattern: "*"
   owner: ec2-user
   mode: 744
   type:
    - directory
hooks:
  ApplicationStart:
   - location: scripts/start_bot
     timeout: 300
     runas: ec2-user