#!/bin/bash

pwd

export NVM_DIR="/home/ec2-user/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm use 16

npm install pm2@latest -g

cd /home/ec2-user/WhaleBot

pwd

npm i
pm2 stop WhaleBot
pm2 start node index.js --name "WhaleBot"